name: settings_clone
description: "Samsung-style Settings app clone (front-end only) in Flutter. Includes 데이터/핫스팟 사용량 flows and an editor."
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_icon.png

flutter_icons:
  android: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1976D2"
  # Note: for simplicity we use a single image and background.
