name: Build Android APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter version
        run: flutter --version

      - name: Create Flutter project skeleton
        run: |
          rm -rf settings_clone || true
          flutter create settings_clone --platforms=android --project-name settings_clone --org com.example --overwrite

      - name: Copy source & assets & pubspec into project
        run: |
          rsync -av --delete app_src/lib/ settings_clone/lib/
          rsync -av --delete app_src/assets/ settings_clone/assets/
          cp app_src/pubspec.yaml settings_clone/pubspec.yaml
          if [ -f app_src/analysis_options.yaml ]; then cp app_src/analysis_options.yaml settings_clone/analysis_options.yaml; fi

      - name: Get packages
        working-directory: settings_clone
        run: flutter pub get

      - name: Generate launcher icons
        working-directory: settings_clone
        run: flutter pub run flutter_launcher_icons:main

      - name: Build APK (release)
        working-directory: settings_clone
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: settings_clone/build/app/outputs/flutter-apk/app-release.apk
